---
- name: Create
  hosts: all
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command | default('bash -c \"while true; do sleep 10000; done\"') }}"
        privileged: "{{ item.privileged | default(false) }}"
        state: present
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      run_once: true

    - name: Start molecule instance(s)
      ansible.builtin.command:
        cmd: docker start "{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      changed_when: true
      delegate_to: localhost
      run_once: true
