---
- name: Destroy
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove molecule instance(s)
      ansible.builtin.command:
        cmd: docker rm --force "{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      run_once: true
      register: _molecule_destroy
      changed_when: _molecule_destroy.rc == 0
      failed_when: false
