---
name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - "v*.*.*"  # Semantic versioning tags

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7.0.1

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  publish:
    name: Publish to Galaxy
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7.0.1

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Import role to Ansible Galaxy
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
        run: |
          uv run ansible-galaxy role import \
            --api-key $GALAXY_API_KEY \
            --force \
            --role-name hermes \
            ${{ github.repository }}
